/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoVideoIdRouteImport } from './routes/video.$videoId'
import { Route as SubjectSubjectIdRouteImport } from './routes/subject.$subjectId'
import { Route as QuizPlaylistIdRouteImport } from './routes/quiz.$playlistId'
import { Route as PlaylistPlaylistIdRouteImport } from './routes/playlist.$playlistId'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoVideoIdRoute = VideoVideoIdRouteImport.update({
  id: '/video/$videoId',
  path: '/video/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdRoute = SubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizPlaylistIdRoute = QuizPlaylistIdRouteImport.update({
  id: '/quiz/$playlistId',
  path: '/quiz/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdRoute = PlaylistPlaylistIdRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/quiz/$playlistId': typeof QuizPlaylistIdRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/video/$videoId': typeof VideoVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/quiz/$playlistId': typeof QuizPlaylistIdRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/video/$videoId': typeof VideoVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/quiz/$playlistId': typeof QuizPlaylistIdRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/video/$videoId': typeof VideoVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/dashboard'
    | '/home'
    | '/playlist/$playlistId'
    | '/quiz/$playlistId'
    | '/subject/$subjectId'
    | '/video/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/dashboard'
    | '/home'
    | '/playlist/$playlistId'
    | '/quiz/$playlistId'
    | '/subject/$subjectId'
    | '/video/$videoId'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/auth'
    | '/dashboard'
    | '/home'
    | '/playlist/$playlistId'
    | '/quiz/$playlistId'
    | '/subject/$subjectId'
    | '/video/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  PlaylistPlaylistIdRoute: typeof PlaylistPlaylistIdRoute
  QuizPlaylistIdRoute: typeof QuizPlaylistIdRoute
  SubjectSubjectIdRoute: typeof SubjectSubjectIdRoute
  VideoVideoIdRoute: typeof VideoVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$videoId': {
      id: '/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof VideoVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId': {
      id: '/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof SubjectSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$playlistId': {
      id: '/quiz/$playlistId'
      path: '/quiz/$playlistId'
      fullPath: '/quiz/$playlistId'
      preLoaderRoute: typeof QuizPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  PlaylistPlaylistIdRoute: PlaylistPlaylistIdRoute,
  QuizPlaylistIdRoute: QuizPlaylistIdRoute,
  SubjectSubjectIdRoute: SubjectSubjectIdRoute,
  VideoVideoIdRoute: VideoVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
